# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: andarroyave-hostinger


variables:
  - group: andarroyave_com
  
steps:

- script: |
    echo Building docker image $(version).
    sudo docker build -t andarroyave.com:$(version) .
  displayName: 'Build docker image'

- script: |
    echo Deploying docker image $(version).
    sudo docker stop andarroyave
    sudo docker rm andarroyave
    sudo docker run -d -p 3000:3000 -p 8000:8000 --name andarroyave andarroyave.com:$(version)
    


    
